version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: laravel_app
    volumes:
      - .:/var/www
    depends_on:
      - mongo
      - redis
    networks:
      - laravel_net

  nginx:
    image: nginx:stable
    container_name: laravel_nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel_net

  mongo:
    image: mongo
    container_name: laravel_mongo
    ports:
      - "27017:27017"
    networks:
      - laravel_net

  redis:
    image: redis
    container_name: laravel_redis
    ports:
      - "6379:6379"
    networks:
      - laravel_net

networks:
  laravel_net:
    driver: bridge
